# Generated by Django 5.0.4 on 2024-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[('0', 'female'), ('1', 'male')], default='1')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
