# Generated by Django 5.0.4 on 2024-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_remove_employee_employeeemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
