# Generated by Django 5.0.4 on 2024-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
